// <auto-generated />
using System;
using GroupFlights.WorkloadManagement.Core.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GroupFlights.WorkloadManagement.Core.Data.EF.Migrations
{
    [DbContext(typeof(WorkloadsDbContext))]
    partial class WorkloadsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workloads")
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GroupFlights.WorkloadManagement.Core.Models.CashierWorkloadAssignment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkloadSourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkloadType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AssignmentId");

                    b.HasIndex("WorkloadType", "WorkloadSourceId")
                        .IsUnique();

                    b.HasIndex("CashierId", "WorkloadType", "WorkloadSourceId")
                        .IsUnique();

                    b.ToTable("Workloads", "workloads");
                });
#pragma warning restore 612, 618
        }
    }
}
